INSERT INTO product(name, description, brand, model, category, stock, price) VALUES
('Smartphone', 'Powerful smartphone with high-quality camera', 'Samsung', 'Galaxy S21', 'Gadget', 100, 10000000),
('Laptop', 'Thin and lightweight laptop for work and entertainment', 'Dell', 'XPS 13', 'Computer', 50, 20000000),
('Running Shoes', 'Comfortable and durable shoes for running', 'Nike', 'Air Zoom Pegasus 38', 'Sport', 80, 1500000),
('Sunglasses', 'Stylish sunglasses with UV protection', 'Ray-Ban', 'Wayfarer', 'Fashion', 120, 500000),
('Backpack', 'Spacious backpack for daily use or travel', 'The North Face', 'Jester', 'Outdoor', 70, 750000),
('Coffee Maker', 'Automatic coffee maker for brewing delicious coffee', 'Keurig', 'K-Elite', 'Home Appliance', 40, 3000000),
('Gaming Mouse', 'High-performance mouse for gaming enthusiasts', 'Logitech', 'G502 Hero', 'Gaming', 90, 1000000),
('Dumbbells', 'Set of dumbbells for strength training at home', 'Bowflex', 'SelectTech 552', 'Fitness', 60, 2000000),
('Digital Camera', 'Compact digital camera for capturing memorable moments', 'Canon', 'PowerShot G7 X Mark III', 'Photography', 30, 7000000),
('Hiking Boots', 'Sturdy hiking boots for outdoor adventures', 'Merrell', 'Moab 2', 'Outdoor', 50, 2500000),
('Smart Watch', 'Feature-rich smartwatch for tracking fitness and notifications', 'Apple', 'Watch Series 6', 'Wearable', 80, 8000000),
('Blender', 'Versatile blender for making smoothies and soups', 'Vitamix', 'Explorian E310', 'Kitchen Appliance', 45, 4000000),
('Headphones', 'Premium headphones with noise cancellation feature', 'Sony', 'WH-1000XM4', 'Audio', 65, 3000000),
('Yoga Mat', 'High-quality yoga mat for practicing yoga at home or studio', 'Liforme', 'Yoga Mat', 'Sport', 100, 1000000),
('Watch', 'Elegant wristwatch for both formal and casual occasions', 'Seiko', 'Presage', 'Fashion', 55, 3500000),
('Air Purifier', 'Efficient air purifier for maintaining clean indoor air', 'Dyson', 'Pure Cool TP04', 'Home Appliance', 35, 6000000),
('Tennis Racket', 'Professional tennis racket for competitive matches', 'Wilson', 'Pro Staff RF97 Autograph', 'Sport', 75, 1800000),
('Vacuum Cleaner', 'Powerful vacuum cleaner for thorough cleaning', 'Shark', 'Navigator Lift-Away', 'Home Appliance', 40, 4500000),
('Cookware Set', 'Complete set of cookware for versatile cooking options', 'Cuisinart', 'Multiclad Pro', 'Kitchen Appliance', 65, 7000000),
('Bicycle', 'Durable bicycle for commuting or recreational cycling', 'Trek', 'FX 2 Disc', 'Outdoor', 55, 3000000),
('Golf Clubs', 'Premium golf clubs for improving your game', 'Callaway', 'Rogue X', 'Sport', 45, 5000000),
('Portable Speaker', 'Portable speaker with powerful sound for outdoor use', 'JBL', 'Flip 5', 'Audio', 85, 1500000),
('Handbag', 'Stylish handbag for carrying essentials in fashion', 'Coach', 'Signature Jacquard', 'Fashion', 70, 4000000),
('Electric Toothbrush', 'Advanced electric toothbrush for effective oral hygiene', 'Philips', 'Sonicare DiamondClean', 'Home Appliance', 50, 2000000),
('Television', 'High-definition television for immersive viewing experience', 'Samsung', 'QLED Q80T', 'Home Appliance', 60, 12000000),
('Camping Tent', 'Spacious camping tent for outdoor adventures', 'Coleman', 'Sundome', 'Outdoor', 40, 2500000),
('Sneakers', 'Classic sneakers for everyday comfort and style', 'Adidas', 'Superstar', 'Fashion', 90, 2000000),
('Electric Scooter', 'Foldable electric scooter for convenient urban commuting', 'Xiaomi', 'Mi Electric Scooter', 'Gadget', 65, 3000000),
('Fitness Tracker', 'Fitness tracker for monitoring activity levels and health metrics', 'Fitbit', 'Charge 4', 'Wearable', 80, 1500000),
('Desk Lamp', 'Modern desk lamp with adjustable brightness levels', 'IKEA', 'Jansjo', 'Home Decor', 55, 800000);
